import {Montserrat} from "next/font/google"
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "800"]
})

export const metadata = {
  title: "Payme Support",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased w-full h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
